export const Capitais = [
    "Campo Grande",
    "São Paulo",
    "Curitiba",
    "Florianópolis",
    "Rio Branco",
    "Macapá",
    "Manaus",
    "Belém",
    "Porto Velho",
    "Boa Vista",
    "Palmas",
    "Maceió",
    "Salvador",
    "Fortaleza",
    "São Luís",
    "João Pessoa",
    "Recife",
    "Teresina",
    "Natal",
    "Aracaju",
    "Goiás",
    "Goiânia",
    "Cuiabá",
    "Brasília",
    "Vitória",
    "Belo Horizonte",
    "Rio de Janeiro",
    "Porto Alegre"
];